// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("EchoDemo")]
[assembly: AssemblyDescription("Demo for the winmm.dll wrapper")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("WinMM.Net")]
[assembly: AssemblyCopyright("Copyright © 2010 John Gietzen")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: CLSCompliant(true)]

[assembly: ComVisible(false)]

[assembly: Guid("e45ad9f9-6edf-4de1-a997-dd39316c1074")]

[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
