// <auto-generated />

namespace EchoDemo
{
    partial class MainView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainView));
            this.SpeakerPicture = new System.Windows.Forms.PictureBox();
            this.LevelBar = new System.Windows.Forms.ProgressBar();
            this.LevelLabel = new System.Windows.Forms.Label();
            this.InDeviceLabel = new System.Windows.Forms.Label();
            this.InDevice = new System.Windows.Forms.Label();
            this.OutDevice = new System.Windows.Forms.Label();
            this.OutDeviceLabel = new System.Windows.Forms.Label();
            this.InChannels = new System.Windows.Forms.Label();
            this.OutChannels = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.SpeakerPicture)).BeginInit();
            this.SuspendLayout();
            // 
            // SpeakerPicture
            // 
            this.SpeakerPicture.Image = global::EchoDemo.Properties.Resources.arts_control_icon;
            this.SpeakerPicture.Location = new System.Drawing.Point(12, 12);
            this.SpeakerPicture.Name = "SpeakerPicture";
            this.SpeakerPicture.Size = new System.Drawing.Size(128, 128);
            this.SpeakerPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.SpeakerPicture.TabIndex = 0;
            this.SpeakerPicture.TabStop = false;
            // 
            // LevelBar
            // 
            this.LevelBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.LevelBar.Location = new System.Drawing.Point(146, 28);
            this.LevelBar.MarqueeAnimationSpeed = 0;
            this.LevelBar.Maximum = 32768;
            this.LevelBar.Name = "LevelBar";
            this.LevelBar.Size = new System.Drawing.Size(309, 23);
            this.LevelBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
            this.LevelBar.TabIndex = 1;
            // 
            // LevelLabel
            // 
            this.LevelLabel.AutoSize = true;
            this.LevelLabel.Location = new System.Drawing.Point(146, 12);
            this.LevelLabel.Name = "LevelLabel";
            this.LevelLabel.Size = new System.Drawing.Size(36, 13);
            this.LevelLabel.TabIndex = 0;
            this.LevelLabel.Text = "Level:";
            // 
            // InDeviceLabel
            // 
            this.InDeviceLabel.AutoSize = true;
            this.InDeviceLabel.Location = new System.Drawing.Point(146, 66);
            this.InDeviceLabel.Margin = new System.Windows.Forms.Padding(3, 12, 3, 0);
            this.InDeviceLabel.Name = "InDeviceLabel";
            this.InDeviceLabel.Size = new System.Drawing.Size(56, 13);
            this.InDeviceLabel.TabIndex = 2;
            this.InDeviceLabel.Text = "In Device:";
            // 
            // InDevice
            // 
            this.InDevice.AutoSize = true;
            this.InDevice.Location = new System.Drawing.Point(216, 66);
            this.InDevice.Name = "InDevice";
            this.InDevice.Size = new System.Drawing.Size(59, 13);
            this.InDevice.TabIndex = 3;
            this.InDevice.Text = "#WaveIn#";
            // 
            // OutDevice
            // 
            this.OutDevice.AutoSize = true;
            this.OutDevice.Location = new System.Drawing.Point(216, 104);
            this.OutDevice.Name = "OutDevice";
            this.OutDevice.Size = new System.Drawing.Size(67, 13);
            this.OutDevice.TabIndex = 5;
            this.OutDevice.Text = "#WaveOut#";
            // 
            // OutDeviceLabel
            // 
            this.OutDeviceLabel.AutoSize = true;
            this.OutDeviceLabel.Location = new System.Drawing.Point(146, 104);
            this.OutDeviceLabel.Margin = new System.Windows.Forms.Padding(3, 12, 3, 0);
            this.OutDeviceLabel.Name = "OutDeviceLabel";
            this.OutDeviceLabel.Size = new System.Drawing.Size(64, 13);
            this.OutDeviceLabel.TabIndex = 4;
            this.OutDeviceLabel.Text = "Out Device:";
            // 
            // InChannels
            // 
            this.InChannels.AutoSize = true;
            this.InChannels.Location = new System.Drawing.Point(216, 79);
            this.InChannels.Name = "InChannels";
            this.InChannels.Size = new System.Drawing.Size(65, 13);
            this.InChannels.TabIndex = 6;
            this.InChannels.Text = "#Channels#";
            // 
            // OutChannels
            // 
            this.OutChannels.AutoSize = true;
            this.OutChannels.Location = new System.Drawing.Point(216, 117);
            this.OutChannels.Name = "OutChannels";
            this.OutChannels.Size = new System.Drawing.Size(65, 13);
            this.OutChannels.TabIndex = 7;
            this.OutChannels.Text = "#Channels#";
            // 
            // MainView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(467, 152);
            this.Controls.Add(this.OutChannels);
            this.Controls.Add(this.InChannels);
            this.Controls.Add(this.OutDevice);
            this.Controls.Add(this.OutDeviceLabel);
            this.Controls.Add(this.InDevice);
            this.Controls.Add(this.InDeviceLabel);
            this.Controls.Add(this.LevelLabel);
            this.Controls.Add(this.LevelBar);
            this.Controls.Add(this.SpeakerPicture);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "MainView";
            this.Text = "Echo";
            ((System.ComponentModel.ISupportInitialize)(this.SpeakerPicture)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox SpeakerPicture;
        private System.Windows.Forms.ProgressBar LevelBar;
        private System.Windows.Forms.Label LevelLabel;
        private System.Windows.Forms.Label InDeviceLabel;
        private System.Windows.Forms.Label InDevice;
        private System.Windows.Forms.Label OutDevice;
        private System.Windows.Forms.Label OutDeviceLabel;
        private System.Windows.Forms.Label InChannels;
        private System.Windows.Forms.Label OutChannels;
    }
}

